### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by JayFate** [JayFate/note#1]
你也可以查看所有的容器，包括没有在运行状态的容器，使用 `docker ps -a` 命令

**Comment by JayFate** [comment]
```bash
# 停止容器  2139   2139
docker stop 2139 1e2a

# 删除容器
docker rm c3a2 b6d4 3363

# 停止并删除所有的容器
docker ps -aq | xargs docker stop | xargs docker rm

# 停止并删除所有的正在运行的容器
docker ps -q | xargs docker stop | xargs docker rm

# 进入容器
docker exec -it dda5 bash
```

**Comment by JayFate** [comment]
# 使用 `docker build` 来构建 web 应用
```bash
https://docker-training-labs.readthedocs.io/en/latest/01-getting-started/docker-machine-commands.html
```

`docker-comopse up`, `docker-comopse start`, `docker-comopse restart` 的区别
https://blog.csdn.net/wangooo/article/details/109362673
https://stackoverflow.com/questions/33715499/what-is-the-difference-between-docker-compose-up-and-docker-compose-start

**Comment by JayFate** [comment]
一个可以直接使用的 `docker-compose.yml`

```yml
version: '3.7'

volumes:
  wp-data:
networks:
  wp-back:

services:

  db:
    image: mysql:5.7
    volumes:
      - wp-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: rootPassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wp-user
       MYSQL_PASSWORD: wp-pass
    ports:
      - 8889:3306
    networks:
      - wp-back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - 3001:80
    networks:
      - wp-back

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8888:80
      - 443:443
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wp-user
       WORDPRESS_DB_PASSWORD: wp-pass
    volumes:
      - ./wordpress-files:/var/www/html
    container_name: wordpress-site
    networks:
      - wp-back
```
